### ISSUE TITLE
No top processes in the RAM module

### ISSUE THREAD

**Issue by ChangCXQ** [exelban/stats#1145]
Memory footprint info, I don't think it's the correct interface, but no matter what I do, it just shows the info as shown in the screenshot.
![WX20221102-233516@2x](https://user-images.githubusercontent.com/107345133/199534089-d063f4e6-0b68-4df8-b904-506ce4b36a4b.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Please share the output of the `top -l 1 -o mem -n 8 -stats pid,command,mem`.

**Comment by ChangCXQ** [comment]
Apple M1，macOS 13.0 (22A380)
Stats 2.7.41
![Uploading WX20221102-234313@2x.png…]()

**Comment by exelban** [comment]
Hmm, very strange. Please try to change the top process number. For example 8 -> 0 -> 8. It will restart the top reader.

**Comment by exelban** [comment]
Also, please check if processes are visible in the CPU module.

**Comment by ChangCXQ** [comment]
> Also, please check if processes are visible in the CPU module.
Process information in the CPU module:
![WX20221103-002342@2x](https://user-images.githubusercontent.com/107345133/199545106-98135397-f1f2-4c7d-8937-75e3f4800f95.png)

**Comment by exelban** [comment]
Only I can do it creates a debug build that will collect the logs to the file. Do you want to help with that?

**Comment by ChangCXQ** [comment]
> Only I can do it creates a debug build that will collect the logs to the file. Do you want to help with that?

Yes, I would love to do that. Because I think Stats is an excellent program and I enjoy using it.

**Comment by exelban** [comment]
Thanks.
Please run that build and open the RAM popup for a few seconds. After that, you will find a file `log.txt` in the `Document` folder. Please share it. It allows figure out why there are no data.

[Stats.dmg.zip](https://github.com/exelban/stats/files/9922499/Stats.dmg.zip)

**Comment by ChangCXQ** [comment]
> Thanks. Please run that build and open the RAM popup for a few seconds. After that, you will find a file `log.txt` in the `Document` folder. Please share it. It allows figure out why there are no data.
> 
> [Stats.dmg.zip](https://github.com/exelban/stats/files/9922499/Stats.dmg.zip)

[log.txt](https://github.com/exelban/stats/files/9922530/log.txt)
I had the RAM window open during that time period at
November 3, 2022, 00:47 CST

**Comment by exelban** [comment]
Thanks. I see the bug.

Please try this build: 
[Stats.dmg.zip](https://github.com/exelban/stats/files/9922657/Stats.dmg.zip)

**Comment by ChangCXQ** [comment]
> Thanks. I see the bug.
> 
> Please try this build: [Stats.dmg.zip](https://github.com/exelban/stats/files/9922657/Stats.dmg.zip)

![WX20221103-010941@2x](https://user-images.githubusercontent.com/107345133/199555624-2713aa1d-af79-4703-8620-9774ffa380c9.png)
Very good, the bug is fixed.

**Comment by exelban** [comment]
It's not fixed yet. I will close the issue when the release with that fix will be available. To prevent duplicating the issue.
Thanks for your help)

**Comment by ChangCXQ** [comment]
> It's not fixed yet. I will close the issue when the release with that fix will be available. To prevent duplicating the issue. Thanks for your help)

Okay, okay, I'm waiting for the new version to be released.
