### ISSUE TITLE
The battery monitor is displayed at startup, even if turned off

### ISSUE THREAD

**Issue by sirburpalot** [exelban/stats#18]
<img width="200" alt="Screenshot 2019-08-11 at 03 18 07" src="https://user-images.githubusercontent.com/1429516/62828102-a9f83900-bbe6-11e9-8822-db29788415ca.png">

**Comment by exelban** [comment]
fixed in [v1.2.9](https://github.com/exelban/stats/releases/tag/v1.2.9)

**Comment by sirburpalot** [comment]
@exelban, I've tried the latest release, and the bug is still there.

**Comment by exelban** [comment]
@sirburpalot it looks like I figured out what goes wrong.
Could you check this version?
[v1.2.10](https://serhiy.s3.eu-central-1.amazonaws.com/Github_repo/stats/Stats.dmg)
