### ISSUE TITLE
[Bug] Icons in the menu bar are not grayed out on the inactive screen (macOS Sequoia)

### ISSUE THREAD

**Issue by au-ganymede** [exelban/stats#2131]
**Bug:**
As in the topic. On an inactive (second) monitor, the Stats icons in the menu bar are not grayed out, unlike the other icons, thus drawing unnecessary attention to themselves.

---

**Details:**
 - Device: **Macbook Pro M3 Max**
 - macOS: **Sequoia 15.0 (24A335)**
 - Application version: **2.11.5**

---

![CleanShot 2024-09-18 at 00 08 34](https://github.com/user-attachments/assets/c3eb6770-1e69-4710-ba37-5fdc09c12435)

**Comment by whusnoopy** [comment]
Same on an other MacBook Pro 16 with M3 Max, macOS 15.0 (24A335), and Stats 2.11.10

**Comment by nicolopadovan** [comment]
Same on MacBook Pro 2021 M1 Max, MacOS 15.0.0, Stats 2.11.0

**Comment by gmcinalli** [comment]
Confirmed also here, running Stats 2.11.9 on macOS 15.0.0.

<img width="823" alt="image" src="https://github.com/user-attachments/assets/b6522275-1429-40ae-bf76-f8c193884de7">

**Comment by AntonioAEMartins** [comment]
Hi @au-ganymede, @nicolopadovan, @gmcinalli, and @whusnoopy,

I'm also using Stats and encountering the same issue on my machine (MacBook Pro i9 16"). I'll be downloading the repository locally to investigate and attempt to find a solution. Have any of you already done this? If so, what did you discover?

**Comment by au-ganymede** [comment]
@AntonioAEMartins 

It seems it's a bug in Sequoia. 

[From AlDente GitHub:](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/issues/1322#issuecomment-2355317028)

> Thank you for this bug report. We are aware of this issue and have tried to fix it already. Unfortunately, this is a bug of macOS Sequoia, and we have already filed a bug report at Apple since it is not only a problem of AlDente but most Menubar apps that use a different framework to also display more complex data in the Menubar. We hope Apple will fix it soon and will communicate updates here.

**Comment by AntonioAEMartins** [comment]
Hi @au-ganymede,

Thank you for pointing that out regarding the Sequoia bug.If that’s the case, do you think we should close this issue for now and wait for Apple to fix it, or is it worth keeping open for further tracking?

**Comment by exelban** [comment]
@au-ganymede thx for sharing this info

**Comment by au-ganymede** [comment]
@AntonioAEMartins 
I’m not sure, I’ll leave that decision to the moderator. 
If it were up to me, though, I’d probably keep the thread open until Apple fixes the bug, following the example of the statement I mentioned earlier, to avoid duplicate reports.


@exelban 
No problem. 

By the way, thanks to the email notification of your comment, I now know exactly who's listed under the "Allow in the Background" section in System Settings 😅 
I was initially confused, expecting to see the app's name (Stats) instead of the developer's name there 😃

![CleanShot 2024-09-18 at 22 06 34@2x](https://github.com/user-attachments/assets/f1d1c698-33cd-4ab3-8b92-bcf086c8d0da)

**Comment by gmcinalli** [comment]
@au-ganymede Really strange, some other apps works normally here, for example, look at KeepingYouAwake (the coffee cup) in my screenshot.

**Comment by au-ganymede** [comment]
@gmcinalli From what I understand, this bug affects apps that use non-standard frameworks (rather than the built-in ones) to display complex information in the menubar. Apps like Stats, AlDente, and LittleSnitch all fall into this category and are impacted by the issue.

**Comment by exelban** [comment]
@KizzyCode thx, I will try that

**Comment by exelban** [comment]
hi. Please someone check if its fixed in this build:

[Stats.dmg.zip](https://github.com/user-attachments/files/17355853/Stats.dmg.zip)

**Comment by KizzyCode** [comment]
Seems to be fixed for me 🎉

Main screen:
<img width="555" alt="Screenshot 2024-10-13 at 18 47 44" src="https://github.com/user-attachments/assets/1eb21b3c-55d6-4361-ac99-414c2f6dd474">

Secondary screen:
<img width="668" alt="Screenshot 2024-10-13 at 18 47 56" src="https://github.com/user-attachments/assets/b6e754e3-ede6-496b-a4ac-e483898f1b0d">

**Comment by gmcinalli** [comment]
@exelban Resolved!

<img width="393" alt="image" src="https://github.com/user-attachments/assets/a758cf4b-8537-4c62-86a5-0ab449a14532">

**Comment by KingfuChan** [comment]
Issue persists in 2.11.5. MacBook Air 13" (M2), macOS Sequoia (15.0.1)

On active screen:
![image](https://github.com/user-attachments/assets/96c6bb9d-cd1a-49cf-85bf-f120308f9e26)

On inactive screen:
![image](https://github.com/user-attachments/assets/e76d7de4-4efd-41cb-97bd-c2a5de844ccc)

**Comment by fran-6co** [comment]
issue keeps happening for me on my inactive monitor

Stats 2.11.5 – MBP 13" Touchbar 2018 – Sequoia 15.0.1

![image](https://github.com/user-attachments/assets/472a4c5e-23a9-4375-95db-cdac63cd47b5)

**Comment by whusnoopy** [comment]
> Same on an other MacBook Pro 16 with M3 Max, macOS 15.0 (24A335), and Stats 2.11.10

Fixed on MacBook Pro 16 with M3 Max, macOS 15.0.1 (24A348), and Stats 2.11.15

**Comment by sassrobi** [comment]
When "Combined modules" switched on, this bug still exists. Without combined modules, it is indeed fixed. MacBook Pro 16, M3 Pro

**Comment by exelban** [comment]
@sassrobi will fix it, thx
